AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Create EC2, S3, VPC and Subnet along with metadata, parameters and resources using a CloudFormation template.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Network Configuration"
        Parameters:
          - VPCIDP
          - VPCSubnetR
      - Label:
          default: "Compute"
        Parameters:
          - EC2imageIDP
      - Label:
          default: "Storage"
        Parameters:
          - S3bucketnameP

Parameters:
  S3bucketnameP:
    Type: String
    Description: Enter a unique name for the S3 bucket.

  EC2imageIDP:
    Type: String
    Default: ami-
    AllowedValues:
      - ami-
      - ami-
    Description: Select a valid AMI ID (region-specific).

  VPCIDP:
    Type: String
    Default: 10.0.0.0/16
    AllowedValues:
      - 10.0.0.0/16
      - 10.0.0.0/24
    Description: CIDR block for the VPC.

  VPCSubnetR:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR block for the subnet inside the VPC.

Resources:
  CFNVPCR:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCIDP
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Project
          Value: CFN-Implementation

  CFNSubnetR:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref VPCSubnetR
      VpcId: !Ref CFNVPCR
      Tags:
        - Key: Project
          Value: Banking

  CFNS3R:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3bucketnameP
      Tags:
        - Key: Project
          Value: CFN-Implementation

  CFNEC2R:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2imageIDP
      InstanceType: t2.micro
      SubnetId: !Ref CFNSubnetR
      Tags:
        - Key: Project
          Value: CFN-Implementation
